Issue 1 / Update elm-css dependency to latest version
scottcorgan/elm-css-normalize pull request #2
Opened 2016-10-16 18:53 UTC by maxekman

Allows the module to be used with the latest version of elm-css (6.1.0).

Also adds a Stylesheet.elm file for building a css file (for dev), adds content to the readme file and removes the dependency on scottcorgan/elm-html-template which was only used in the example and not when included as a dependency.

2016-10-16 19:01 UTC, maxekman commented
By the way, I diffed the CSS file before and after the changes and it comes out clean.

2016-10-17 14:19 UTC, scottcorgan requested changes
A few comments to make this a bit easier for everyone. Thanks for the hard work!

2016-10-17 14:19 UTC, scottcorgan commented on README.md
> +## Usage
I'd prefer Usage docs be restricted to examples in the Elm file's comments/docs. It's a typical Elm pattern to have a minimal README and put everything in the Elm files.

This is mostly so it shows up correctly on the Elm Package manager

2016-10-17 14:19 UTC, scottcorgan commented on README.md
> +## Development/Testing
👍 This is good to stay in the README

2016-10-17 14:19 UTC, scottcorgan commented on README.md
> +Note that github.com/scottcorgan/elm-html-template is required for development/testing and has to be manually added.
💭 Just a thought. Maybe we add a `elm-package.json` file the the examples directory that includes the html template. Then there's less manual work when running `elm-reactor`.

2016-10-17 14:38 UTC, maxekman commented
Thanks for the comments, will address them all soon. I did not know about the best practices for Elm package docs, thanks for pointing that out.

2016-10-17 17:10 UTC, maxekman commented on README.md
> +## Usage
Totally missed that there were docs already! I guess I'm just used to reading docs on Github. I'll add a link to the package docs instead then.

2016-10-17 17:22 UTC, maxekman commented
I think I have addressed all comments in a sensible way. Don't forget to bump the version of this package in `elm-package.json` in the examples folder after bumping the real package version!

2016-10-19 13:03 UTC, scottcorgan approved these changes

2016-10-19 13:03 UTC, merged

2016-10-19 13:03 UTC, scottcorgan commented
@maxekman this looks amazing! Thank you!

2016-10-19 13:10 UTC, maxekman commented
Awesome! Now I can use this package instead of a copy of the Normalize.elm file.

2016-10-19 18:43 UTC, maxekman commented
Worked like a charm to include it as a package with elm-css 6.1.0!